import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/context/AuthProvider";
import SocketProvider from "@/context/SocketProvider";
// import { QueryClient, QueryClientProvider } from "react-query";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
//   const queryClient = QueryClient();
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className} suppressHydrationWarning>
        <AuthProvider>
          <SocketProvider>
            {/* <QueryClientProvider client={queryClient}> */}
              {children}
            {/* </QueryClientProvider> */}
          </SocketProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
